export type Expense = {
  id: number;
  importId: number | null;
  categoryId: number | null;
  categoryName: string | null;
  date: string | null;
  merchant: string | null;
  description: string;
  amount: number;
  currency: string;
  amountCrc: number | null;
  amountUsd: number | null;
  conversionStatus: string;
  paymentMethod: string | null;
  documentNumber: string | null;
  confidence: number | null;
  needsReview: boolean;
  notes: string | null;
  createdAt: string;
  updatedAt: string;
};
